// Code generated by Kitex v0.9.1. DO NOT EDIT.

package judgeservice

import (
	"context"
	judgesvc "github.com/ahaostudy/onlinejudge/kitex_gen/judgesvc"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Judge(ctx context.Context, req *judgesvc.JudgeRequest, callOptions ...callopt.Option) (r *judgesvc.JudgeResponse, err error)
	UploadCode(ctx context.Context, req *judgesvc.UploadCodeRequest, callOptions ...callopt.Option) (r *judgesvc.UploadCodeResponse, err error)
	DeleteCode(ctx context.Context, req *judgesvc.DeleteCodeRequest, callOptions ...callopt.Option) (r *judgesvc.DeleteCodeResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kJudgeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kJudgeServiceClient struct {
	*kClient
}

func (p *kJudgeServiceClient) Judge(ctx context.Context, req *judgesvc.JudgeRequest, callOptions ...callopt.Option) (r *judgesvc.JudgeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Judge(ctx, req)
}

func (p *kJudgeServiceClient) UploadCode(ctx context.Context, req *judgesvc.UploadCodeRequest, callOptions ...callopt.Option) (r *judgesvc.UploadCodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadCode(ctx, req)
}

func (p *kJudgeServiceClient) DeleteCode(ctx context.Context, req *judgesvc.DeleteCodeRequest, callOptions ...callopt.Option) (r *judgesvc.DeleteCodeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteCode(ctx, req)
}
